### ISSUE TITLE
Two details in main doc page (https://docs.clamav.net)

### ISSUE THREAD

**Issue by q2dg** [Cisco-Talos/clamav#1156]
When it says "Supported platforms", Windows 11 is not listed
When it says "Related products", Immunet has been closed
Thanks!

**Comment by micahsnyder** [comment]
That's a good point regarding Immunet being closed. I have removed it from docs: https://github.com/Cisco-Talos/clamav-documentation/commit/9b842dc535c768dfdc65bb519984fab30a19c80c
https://docs.clamav.net/#related-products 

Re: Windows 11.  Generally speaking, we support the last 2 major releases for each of the listed operating systems.  That list, specifically, is for the systems that we actively test. For Windows, right now those are Windows 10 and 7, for both 64bit and 32bit.  We don't actively test Windows 11, yet.  Early on it was difficult to set up because of the TPM requirements, and we haven't set it up since.  But the from ClamAV's perspective, not much has changed between 10 and 11, so it should work fine.  And I can confirm I do ClamAV development on Windows 11 without issues.
