### ISSUE TITLE
I am experiencing bus errors after download and while running clam av on termux x11. Please provide a fix.

### ISSUE THREAD

**Issue by Vj9977** [Cisco-Talos/clamav#1179]
Describe the bug
----------------

Replace this text with a clear and concise description of the bug or feature request.

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
@Vj9977 your issue description lacks detail.  It is just template text.  For this reason, and the reasons below, I am closing this issue. 

A bus error when scanning a file may be a vulnerability.  If it is reproducible with a specific file then that may represent a vulnerability and I would request that you report the issue with the required details needed to reproduce the issue.  See our security policy for details on how to report vulnerabilities: https://github.com/Cisco-Talos/clamav/security/policy

I would note that we do note support termux x11 or android.  We cannot test with it so we will not be able to reproduce or fix any issue unique to this environment. If this is the case, we will likely reject the report.  However, if the issue affects ARM64 linux, then we may be able to fix it.

If the bus errors occur with every scan, or most scans, then it wouldn't be a vulnerability.  In this case, you may report the details here or in a new issue.  I imagine that in this case it would likely an issue with your build or an issue with support for termux x11, and because we lack experience and ability to support this platform, we still may not be able to help.  But someone else from the community may be able to.

**Comment by Vj9977** [comment]
Thank your for your response I have noted it and will stop using the
program on my phone as it is not compatible.
