### ISSUE TITLE
Website issue

### ISSUE THREAD

**Issue by ineuw** [Cisco-Talos/clamav#1267]
The left and right side panels of the clamav documentation webpage cover access to controls or options like copying a code textbox. The image displays the panel covering the left side of the screen, and the right panel is identical.

![clamav_webpage_covers_code_example_access](https://github.com/Cisco-Talos/clamav/assets/10367016/8347ac94-f412-493f-80d8-8852e1b5127f)

**Comment by micahsnyder** [comment]
The width of the panel seems to be too wide and is causing problems.  

You should also be able to work around it if you are able to make your browser window wider.  Of course, if your screen isn't wide enough, then never mind.

I believe I made this panel wider in the past so that it will correctly render some tables on in the appendix.

Which browser are you using?

I'll look into the CSS settings and see if I can find a good solution.

**Comment by micahsnyder** [comment]
Looking at it closer, it seems to me the prev/next page buttons should transition to small buttons instead of side-panel buttons when the page is narrow.  The exact width this occurs is different, unfortunately, from the max-width of the text.  

I do not wish to reduce the content-max-width value or else the tables won't render correctly.  But I cannot find the variable to adjust the width at which the prev/next panel buttons become small buttons. 🫤

As a work-around, I think if you make your window either more narrow, or wider, it will be easier to copypaste.

**Comment by ineuw** [comment]
@micahsnyder, Thanks for the reply. The image was from Firefox in Linux Mint Cinnamon. Then, I tried the page in both Google Chrome and Vivaldi. They are identical (the same product), cover less, but still covered. You could place the two navigation arrows in the center, if it helps. Copying is far more important. I will play around and let you know what can be done. Don't waste your time.

**Comment by micahsnyder** [comment]
@ineuw Our website is generated from this source: https://github.com/Cisco-Talos/clamav-documentation

We use https://rust-lang.github.io/mdBook/

We customized the css a bit.

**Comment by ineuw** [comment]
> We use https://rust-lang.github.io/mdBook/
> We customized the css a bit.

This is very good. Thank you.
