### ISSUE TITLE
ClamAV Conf.

### ISSUE THREAD

**Issue by karascho** [Cisco-Talos/clamav#1409]
1.What is the command line in the terminal to exclude directories.
Please with examples.
2. The same question for maldetect
3. Is there a option to get back to the original configuration after fail configuration.

This should not be so extremly compliclate for user who dont have studied
computer science but just an option to dig deeper.

**Comment by micahsnyder** [comment]
> 1.What is the command line in the terminal to exclude directories. Please with examples. 

if you're using `clamdscan`, then you have to add `ExcludePath` options to your clamd config file. There is no command-line option.  The path you provide is a regex which means if you want to match from the beginning of the path you would start it with a `^`. For example this will exclude the `/tmp` directory, but not `/home/user/tmp`:
```
ExcludePath ^/tmp
```
And if you want to exclude files ending with ".pdf" you could do like this:
```
ExcludePath \.pdf$
```

Regex are very powerful but can be difficult to learn. You'll have to google it to learn more.

If you're using `clamscan` (no `d` in the program name) then it will NOT use the config file and you can use the the `--exclude` or `--exclude-dir` options.  

For example: 
```
clamscan --exclude="\.pdf$" /some/directory
```

> 2. The same question for maldetect 

We don't make maldetect. I have no idea. 

> 3. Is there a option to get back to the original configuration after fail configuration.

This will depend on how you installed clamav (e.g. apt-get on ubuntu versus brew on mac, or apk on alpine). Honestly we don't make those distribution packages either, they're made by third party. So I would have to google it myself or play with it to figure out if it is possible.  I won't know the answer.

Because these are usage questions and not really bug reports, I'm going to close this github issue.  Feel free to ask more questions via the clamav-users mailing list or the discord chat server.

https://docs.clamav.net/#mailing-lists-and-chat
