### ISSUE TITLE
Generating json broken. 

### ISSUE THREAD

**Issue by dbrezack** [Cisco-Talos/clamav#195]
Describe the bug
----------------

--gen-json does nothing

libjson is installed, libjson-dev is installed 

How to reproduce the problem
----------------------------

`clamscan --gen-json .` in a folder containing eicar.com

```
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
PreludeAnalyzerName = "ClamAV"
LogFile = "/var/log/clamav/clamav.log"
LogFileMaxSize = "4294967295"
LogTime = "yes"
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
LocalSocket = "/var/run/clamav/clamd.ctl"
LocalSocketGroup = "clamav"
LocalSocketMode = "666"
MaxConnectionQueueLength = "15"
MaxThreads = "12"
ReadTimeout = "180"
SendBufTimeout = "200"
SelfCheck = "3600"
User = "clamav"
BytecodeTimeout = "60000"
MaxScanTime = "120000"
PCREMatchLimit = "10000"
PCRERecMatchLimit = "5000"

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "4294967295"
LogTime = "yes"
LogRotate = "yes"
UpdateLogFile = "/var/log/clamav/freshclam.log"
Checks = "1"
PrivateMirror = "rhn-cap-allen-2.cisco.com"
MaxAttempts = "5"
ScriptedUpdates disabled
ReceiveTimeout = "30"
*** SafeBrowsing is DEPRECATED ***

clamav-milter.conf not found

Software settings
-----------------
Version: 0.103.2
Optional features supported: MEMPOOL IPv6 FRESHCLAM_DNS_FIX AUTOIT_EA06 BZIP2 LIBXML2 PCRE ICONV JSON JIT

Database information
--------------------
Database directory: /var/lib/clamav
bytecode.cvd: version 331, sigs: 94, built on Thu Sep 19 12:12:33 2019
main.cvd: version 59, sigs: 4564902, built on Mon Nov 25 08:56:15 2019
daily.cvd: version 26025, sigs: 4332551, built on Tue Dec 22 07:51:35 2020
Total number of signatures: 8897547

Platform information
--------------------
uname: Linux 5.4.12-050412-generic #202001141531 SMP Tue Jan 14 20:35:00 UTC 2020 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
Full OS version: Ubuntu 18.04.3 LTS
zlib version: 1.2.11 (1.2.11), compile flags: a9
Triple: x86_64-pc-linux-gnu
CPU: generic, Little-endian
platform id: 0x0a217b7b0807050001070500

Build information
-----------------
GNU C: 7.5.0 (7.5.0)
GNU C++: 7.5.0 (7.5.0)
CPPFLAGS: -Wdate-time -D_FORTIFY_SOURCE=2
CFLAGS: -g -O2 -fdebug-prefix-map=/build/clamav-ol9PT3/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: -g -O2 -fdebug-prefix-map=/build/clamav-ol9PT3/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64
LDFLAGS: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
Configure: '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--libexecdir=/usr/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-ol9PT3/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-ol9PT3/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed' '--with-dbdir=/var/lib/clamav' '--sysconfdir=/etc/clamav' '--disable-clamav' '--disable-unrar' '--enable-milter' '--enable-dns-fix' '--with-libjson' '--with-system-libmspack' '--with-libcurl=/usr' '--with-gnu-ld' '-with-system-llvm=/usr/bin/llvm-config-3.9' '--with-llvm-linking=dynamic' '--with-systemdsystemunitdir=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'OBJCFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-ol9PT3/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security'
sizeof(void*) = 8
Engine flevel: 123, dconf: 123
```

**Comment by micahsnyder** [comment]
The `--gen-json` feature wasn't really developed with public use in mind, and isn't very well documented.  The JSON will appear on the terminal if you use the option with `--debug` mode (though it may be truncated if its very long), and it will appear in a file named "metadata.json" in the scan temp directory if you use `--leave-temps`.  You can use the `--tempdir=/some/path` option to customize the temp directory location.

**Comment by dbrezack** [comment]
Hmmmmm. That works. What would be the level of effort to turn this into an actual feature ?

**Comment by micahsnyder** [comment]
Per our offline conversation, I understand that you were hoping the generated JSON would be a more machine-friendly response containing the scan verdict.  While I think that'd be neat, that's unfortunately not what this does.  The generated JSON here is metadata about a scan. It will include the verdict, but it includes a LOT more, such office document metadata, if documents contain macros, basic details about each file found within a scanned file (eg files in an archive), etc.

The format of the JSON generated doesn't adhere to any specific schema and is likely to change.  We use it for some internal processing tasks and I often use it for triaging new malware samples or attempting to understand ClamAV scan behavior when something isn't working right.  I would say it's more of a development and debugging tool.  Honestly I think we should mark this option as "not for use in production" or something to discourage anyone from relying on it.

Anyways. I'm going to close this issue because it's not what you're looking for.  You could continue to use `clamscan` and attempt to review `stdout` for `FOUND`, `OK`, or `ERROR`.  But a better option would be to submit scans to a `clamd` server.  This operates over a socket connection (Unix socket or TCP socket).  See https://docs.clamav.net/manual/Usage/Scanning.html#clamd for some documentation about `clamd`.  The online documentation presently lacks some of the finer details found in the man page (i.e. `man clamd`, source here: https://github.com/Cisco-Talos/clamav/blob/dev/0.104/docs/man/clamd.8.in).  If you do end up working with it and have time to help improve our online documentation, the docs are also open source and you can submit PR's, here: https://github.com/Cisco-Talos/clamav-documentation

_Caution_: One word of caution though, the socket is not authenticated or encrypted, so do not expose it to any users or network which you do not trust.
