### ISSUE TITLE
clamd testing failed

### ISSUE THREAD

**Issue by frans54** [Cisco-Talos/clamav#223]
----------------
clamd version 0.104-rc failing tests. See also clamav-users at the list.
[LastTest.log](https://github.com/Cisco-Talos/clamav/files/6880583/LastTest.log)

**Comment by micahsnyder** [comment]
Thanks for submitting the report @frans54 

To summarize, it seems like there are two related issues triggered by a build in a symlinked directory.

1. the "check_clamd" test is failing because one of the tests within expects the original full path to be in the clamd response

2. The Exclude test for clamd is failing. The file which we tried to exclude isn't being excluded.
