### ISSUE TITLE
Missing --disable-yara option in CMake

### ISSUE THREAD

**Issue by arjendekorte** [Cisco-Talos/clamav#243]
In the 'old' configure options, there used to be an option to disable Yara completely. I couldn't find a replacement in the CMake options. Is this intentional?

**Comment by micahsnyder** [comment]
This is intentional. We have made some similar changes by making libjson-c, libxml2, libpcre2, and libbz2 required as well. 

While our Yara rule support is in dire shape and desperately needs our attention, removing the ability to disable it at build-time reduces build-configuration complexity which means fewer build-permutations to test (and to support). 

Build configurations are more difficult and much more time consuming to test than config file options and command line options. 

I would be open to adding clamd.conf and clamscan command line options to disable yara support instead, if this is something you really need.

**Comment by micahsnyder** [comment]
@arjendekorte if you or anyone else has a strong opinion about disabling yara support through clamd.conf or a clamscan command line option, feel free to open a new ticket.  Since this ticket was more of a question, I'll close this ticket.

**Comment by arjendekorte** [comment]
There seems to be a licensing problem with the existing yara code:

> We need to keep Yara disabled, for legal reasons. It is under Apache license which is incompatible to the GPLv2 that is used by ClamAV. Yara maintainers changed the license to 3-clause BSD five years ago, but ClamAV still uses an older version that is under the old license.

Due to the above, submission of clamav-0.104.0 was declined.

**Comment by rma-x** [comment]
Has the licensing conflict (Apache Version 2.0 vs. GPL Version 2) that used to be the reason for SUSE to use `--disable-yara` been solved in the meantime?

Unfortunately the Bugzilla item that handled this topic does not seem to be available any longer:
https://bugzilla.clamav.net/show_bug.cgi?id=11336
IIRC it was promised in the Bugzilla discussion that an exception similar to that for OpenSSL would get added to the `COPYING.txt` file of ClamAV, but that does not seem to have happened as of ClamAV 1.3.0.

**Comment by micahsnyder** [comment]
We certainly discussed adding an exception similar to that for OpenSSL. But after I met with a couple of Cisco lawyers on the topic, we decided that it wasn't worth adding the exception, considering Yara changed their license and we planned/plan to update our Yara-derived code.

The licensing conflict does not affect the Yara project, but affects the "free-ness" of the ClamAV source code.  Adding the license exception wouldn't change that.  It would really just be a declaration that we're fine with it.  That is to say, no one would care to take legal action against ClamAV because of this conflict.  

Since Yara changed their license -- I think the whole thing is very silly.
