### ISSUE TITLE
clamav 0.104.0-rc2 uses wrong case for documentation directory

### ISSUE THREAD

**Issue by bleve** [Cisco-Talos/clamav#257]
It uses path /usr/share/doc/ClamAV/html on linux. When source file is clamav directory should also be lower case matching package name.

**Comment by arjendekorte** [comment]
You can change this path through the `-DCMAKE_INSTALL_DOCDIR` option to specify a different path

**Comment by bleve** [comment]
This bug report was about wrong default value.

**Comment by arjendekorte** [comment]
You make the assumption that there is a 'correct' default and everything else 'wrong'. Where does it say that parts of the packagename must not be capitalized? In (open)SUSE and Alpine Linux for instance, the ClamAV documentation must be installed in `/usr/share/doc/packages/clamav` (and not `/usr/share/doc/clamav`).

**Comment by bleve** [comment]
You just proved my point :) All those expect lower case clamav.

**Comment by arjendekorte** [comment]
No, I did not. The fact that some distributions use lowercase, doesn't mean any other notation is wrong. What I did prove, is that there is not a generally accepted default path, so there is not a sane default anyway.

**Comment by micahsnyder** [comment]
As @arjendekorte noted, you can and will probably need to customize the path using `CMAKE_INSTALL_DOCDIR` just because every distro has different expectations.  Since that's easy, and most people will be doing it anyhow, I don't think it's worth creating a default for clamav.  Our current setting with the mixed-case is just what CMake comes up with based on the project name. 

To help folks out, I've added a note about using `-D CMAKE_INSTALL_DOCDIR`, and also added detail on how to have CMake skip the RPATH stuff, here: https://docs.clamav.net/manual/Installing/Installing-from-source-Unix.html#a-linux-distribution-style-build
