### ISSUE TITLE
Bypassing the AV (potential RCE)

### ISSUE THREAD

**Issue by nallathambim** [Cisco-Talos/clamav#260]
We identified that it is possible to evade the scanner being used to scan the file. It is possible to craft a malicious .hta file that connects back to attacker’s server upon opening the file from the client side.
The file uses shell code to do this. 

[Scanning with Malicious hta file.docx](https://github.com/Cisco-Talos/clamav/files/7023513/Scanning.with.Malicious.hta.file.docx)

**Comment by finchy** [comment]
Please follow the instructions here:

https://github.com/Cisco-Talos/clamav/security/policy

**Comment by micahsnyder** [comment]
We have thoroughly reviewed the issue as reported, in such a way we now understand it completely.

I have changed the issue title because this issue does not describe a possible remote code execution vulnerability in ClamAV, but instead describes your concern regarding ClamAV's abilities to decode, decrypt, and detect (alert on) C# shellcode that has been encrypted, base64 encoded, and embedded in Javascript within an HTML .hta file.

I'm leaving this issue closed because I believe the best option is for my team to determine the best way to handle such scenarios, and then determine the time and effort required to implement such dynamic decoding, decryption and analysis. At this time, we can’t make any commitments as to WHEN this will be implemented, and IF it will be implemented (as a new feature) at all.

Going forward, we would appreciate if future reports about perceived vulnerabilities in ClamAV were to be routed through the Cisco PSIRT – the Product Security Incident Response Team. Information on how to contact the Cisco PSIRT, including how to encrypt sensitive information to prevent snooping/capture while in transit, can be found at https://tools.cisco.com/security/center/resources/security_vulnerability_policy.html#roosfassv

We sincerely appreciate you taking the time to report this issue to us, and we encourage you to continue to report any additional security issues you might find using the above contact information.
