### ISSUE TITLE
sample configuration files in wrong directory on 0.104-rc2

### ISSUE THREAD

**Issue by bigio** [Cisco-Talos/clamav#270]
As per Filesystem Hierarchy Standard, configuration files shouldn't go to /usr/local/etc on Linux but on /etc.
Changing CMakeLists.txt file should be enough to install files in the correct place.

**Comment by micahsnyder** [comment]
Hardcoding an absolute path like `/etc` isn't portable and doesn't really make sense if you're doing a local installation instead of a system installation (e.g. installing to `$HOME/my_clamav`).

But you can easily modify the install paths yourself. See: https://docs.clamav.net/manual/Installing/Installing-from-source-Unix.html#a-linux-distribution-style-build

Thanks for helping evaluate the release candidate!
