### ISSUE TITLE
Can't install it from source. 

### ISSUE THREAD

**Issue by MandiYang** [Cisco-Talos/clamav#284]
I tried to install clamav 0.104.4 from source.
I ran on terminal:
```
cmake .. \
>     -D CMAKE_INSTALL_PREFIX=/usr \
>     -D CMAKE_INSTALL_LIBDIR=lib \
>     -D APP_CONFIG_DIRECTORY=/etc/clamav \
>     -D DATABASE_DIRECTORY=/var/lib/clamav \
>     -D ENABLE_JSON_SHARED=OFF
```

## Then I ran `sudo cmake --build .` BUT it throwed errors.
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libjson-c.a(json_object.o): relocation R_X86_64_TPOFF32 against `tls_serialization_float_format' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make[2]: *** [libclamav/CMakeFiles/clamav.dir/build.make:2452: libclamav/libclamav.so.9.1.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1485: libclamav/CMakeFiles/clamav.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by micahsnyder** [comment]
Unfortunately the libjson-c.a static library must be compiled with PIC enabled or else it will fail to link into libclamav.so.  

Newer versions of libjson-c have PIC enabled by default and so shouldn't run into this issue. But if you're using an older version of json-c, you'll either need to:
- manually build with with PIC enabled (in which case, why not use a newer version of json-c), or
- use the json-c shared library as you are now doing. 

If you're just building clamav for your own use it's fine to use the json-c shared library. 

The recommendation to use the json-c static library is primarily for the benefit of anyone using or distributing the clamav development libraries for use in other applications that may also use a different JSON library such as jansson.  Applications that link with both jansson and json-c shared libraries may crash at run time due to a identically named symbols.  There is good news that both jansson and json-c projects have recently added symbol versioning so that in the future these two can co-exist in the same application without crashing.
