### ISSUE TITLE
 Clamav clamscan exits with last known signature.

### ISSUE THREAD

**Issue by Toure** [Cisco-Talos/clamav#290]
Describe the bug
----------------

ClamAV has an internal issue in that it will return a finding for malware if it hits the end of some recursion limit in the archive inspection. This causes a false-positive finding typically "ElectroRat".

How to reproduce the problem
----------------------------

The following flags are being used:

$> freshclam

$> clamscan --suppress-ok-results --infected --recursive --allmatch --archive-verbose --tempdir=/analysis_scratch --database=/home/foo/clamav/db --max-filesize=4000m --max-scansize=4000 -l ./scanresult /

freshclam.conf: (content)

DatabaseDirectory /home/foo/clamav/db/
DatabaseOwner foo
DatabaseMirror database.clamav.net

$> clamscan --version
ClamAV 0.103.3

**Comment by micahsnyder** [comment]
I'm not sure what you mean by "last known signature". Can you elaborate?

I tried reproducing the issue using the steps you provided within a centos 8 container with ClamAV 0.103.3 and did not see any alerts. I do see though that you set max-scansize to 4000 bytes instead of 4000M, which I imagine is a typo.  I tried with both options and didn't see any alerts.  

I will need more information in order to help you.  Is there a specific file that you have found which alerts with the Multios.Trojan.ElectroRAT-9823393-0 signature?

**Comment by Toure** [comment]
@micahsnyder Thanks for the prompt response to my issue. Yes, the max-scansize setting was a typo 😄  that should be 4GB as to my comment on the last known signature, what I meant is signature is a false positive it is returned once clamscan exits. It seems like whatever signature that it is working on is in the buffer is returned.

**Comment by Toure** [comment]
Hi @micahsnyder thanks for the prompt response on this issue. What I meant by "last known signature" is that clamscan seems to return the last search signature in its buffer and returns it to the output. I have also noticed a return code of 130 but I can't seem to find it the Enum list of codes.

**Comment by micahsnyder** [comment]
Will close this as a duplicate for #315. This ticket came first, but that one a better description.
