### ISSUE TITLE
freshclam 403

### ISSUE THREAD

**Issue by SlavaGavrilin** [Cisco-Talos/clamav#296]
Hi.
Clamav database protected with Cloudflare DDOS java coockie and it causing update fails.
At least Australia/New Zealand.

**Comment by micahsnyder** [comment]
Can you please provide more details?  Output from `freshclam` or even `freshclam --verbose` will help. 

The output from `clamconf -n` may also help.

**Comment by rajcz** [comment]
Hi, I have this issue too. It is on Centos 6 servers. 
`
Current working dir is /var/lib/clamav
Max retries == 3
ClamAV update process started at Tue Nov  2 09:50:44 2021
Using IPv6 aware code
Querying current.cvd.clamav.net
TTL: 835
Software version from DNS: 0.103.3
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.3
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
If-Modified-Since: Tue, 02 Nov 2021 02:25:58 GMT
main.cvd version from DNS: 62
main.cld is up to date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
daily.cvd version from DNS: 26340
Retrieving http://database.clamav.net/daily-26337.cdiff
Ignoring mirror 104.16.219.84 (due to previous errors)
Ignoring mirror 104.16.218.84 (due to previous errors)
Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
Ignoring mirror 104.16.219.84 (due to previous errors)
Ignoring mirror 104.16.218.84 (due to previous errors)
Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
WARNING: getpatch: Can't download daily-26337.cdiff from database.clamav.net
Retrieving http://database.clamav.net/daily-26337.cdiff
Ignoring mirror 104.16.218.84 (due to previous errors)
Ignoring mirror 104.16.219.84 (due to previous errors)
Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
WARNING: getpatch: Can't download daily-26337.cdiff from database.clamav.net
Retrieving http://database.clamav.net/daily-26337.cdiff
Ignoring mirror 104.16.219.84 (due to previous errors)
Ignoring mirror 104.16.218.84 (due to previous errors)
Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
WARNING: getpatch: Can't download daily-26337.cdiff from database.clamav.net
WARNING: Incremental update failed, trying to download daily.cvd
Whitelisting short-term blacklisted mirrors
Retrieving http://database.clamav.net/daily.cvd
Ignoring mirror 104.16.219.84 (due to previous errors)
Ignoring mirror 104.16.218.84 (due to previous errors)
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:db54)
Ignoring mirror 104.16.219.84 (due to previous errors)
Ignoring mirror 104.16.218.84 (due to previous errors)
Trying host database.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:da54)
Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
WARNING: Can't download daily.cvd from database.clamav.net
`

I try CURL for database.clamav.net/daily.cvd - but there is 403
`
< HTTP/1.1 403 Forbidden
< Date: Tue, 02 Nov 2021 08:53:35 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Connection: keep-alive
< X-Frame-Options: SAMEORIGIN
< Referrer-Policy: same-origin
< Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< X-Content-Type-Options: nosniff
< Server: cloudflare
< CF-RAY: 6a7c22227f2af9ce-PRG
`

**Comment by micahsnyder** [comment]
@rajcz the issue you're having is that you're still using ClamAV 0.100 which exceeded end of life late last week and is now actively blocked from receiving updates. Curl is also blocked to prevent download abuse (downloading when there is no new database update). You will need to update to a newer version of clamav to continue receiving free databases updates. 

See blog.clamav.net/2021/10/clamav-0100-end-of-life-today-and.html for more details.

**Comment by micahsnyder** [comment]
@SlavaGavrilin closing this ticket because we haven't heard back and are unable to help without additional information.
