### ISSUE TITLE
Broken link to README.Docker.md on Docker Hub

### ISSUE THREAD

**Issue by HebaruSan** [Cisco-Talos/clamav#370]
Describe the bug
----------------

https://hub.docker.com/r/clamav/clamav

Click:

![image](https://user-images.githubusercontent.com/1559108/141308603-79b1edc7-5c06-4edb-9121-1583020dd571.png)

Goes to:

https://hub.docker.com/r/clamav/README.Docker.md

![image](https://user-images.githubusercontent.com/1559108/141308685-3bb5e02b-be09-4c94-96c3-06ebcc2489d6.png)

I assume this should be:

https://github.com/Cisco-Talos/clamav/blob/main/README.Docker.md

**Comment by micahsnyder** [comment]
The link comes from a relative markdown link in our Readme: https://github.com/Cisco-Talos/clamav/blob/main/README.md

Perhaps it would be best if we replace all the relative links with links to github as you suggest.

**Comment by micahsnyder** [comment]
It looks like we actually fixed that specific link in the latest version of the readme.  Unfortunately because Docker made the Docker Hub auto-builds feature a paid feature, the Readme on Docker Hub is no longer updated automatically.  

I've gone ahead and updated it manually.  I also fixed a few relative links in the Readme on Docker Hub so the links should all work. 

Thanks for the tip!

**Comment by HebaruSan** [comment]
Looks good now, thanks for the fix!
