### ISSUE TITLE
freshclam fails after HTTP 403 response for CLD file (instead of 404) even though CVD download successful

### ISSUE THREAD

**Issue by trunkshow** [Cisco-Talos/clamav#395]
Long time user with numerous private instances in AWS, all configured with latest Centos 7 clamav version:  ClamAV 0.103.4/26369/Tue Nov 30 04:18:45 2021.   Every instance has the freshclam.conf PrivateMirror setting pointing to a private S3 bucket containing latest downloads of daily.cvd and main.cvd.  Last clamav patch was Nov 15, 2021 and since then every instance is rate limited by CDN, even though all instances are using a private S3 bucket for downloads.  It appears that freshclam is being rate limited and stuck in cool-down for no reason.  These instances should be able to update as often as we want.  I have reviewed all configurations and would like information how to stop rate limiting when using PrivateMirror. 

/var/log/yum.log:Nov 15 07:25:09 Updated: clamav-filesystem-0.103.4-1.el7.noarch
/var/log/yum.log:Nov 15 07:25:09 Updated: clamav-lib-0.103.4-1.el7.x86_64
/var/log/yum.log:Nov 15 07:25:09 Updated: clamav-update-0.103.4-1.el7.x86_64
/var/log/yum.log:Nov 15 07:25:09 Updated: clamav-0.103.4-1.el7.x86_64
/var/log/yum.log:Nov 15 07:25:09 Updated: clamd-0.103.4-1.el7.x86_64
/var/log/yum.log:Nov 15 07:25:09 Updated: clamav-devel-0.103.4-1.el7.x86_64
/var/log/yum.log:Nov 15 07:25:09 Updated: clamav-milter-0.103.4-1.el7.x86_64
/var/log/yum.log:Nov 15 07:25:13 Updated: clamav-data-0.103.4-1.el7.noarch

# configuration
clamconf -n
Checking configuration files in /etc

Config file: clamd.d/scan.conf
------------------------------
LogFile = "/var/log/clamav/clamav.log"
LogTime = "yes"
LogRotate = "yes"
TCPSocket = "3310"

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "2097152"
LogTime = "yes"
LogSyslog = "yes"
LogRotate = "yes"
UpdateLogFile = "/var/log/freshclam.log"
PrivateMirror = "https://redacted.private.s3.bucket.url.amazonaws.com"
Checks 12
MaxAttempts = "1"
NotifyClamd = "/etc/clamd.conf"
ConnectTimeout = "600"
ReceiveTimeout = "3600"
Bytecode no

Config file: mail/clamav-milter.conf
------------------------------------
ERROR: Please edit the example config file /etc/mail/clamav-milter.conf

Software settings
-----------------
Version: 0.103.4

Database information
--------------------
Database directory: /var/lib/clamav
bytecode.cvd: version 333, sigs: 92, built on Mon Mar  8 10:21:51 2021
daily.cvd: version 26369, sigs: 1948295, built on Tue Nov 30 04:18:45 2021
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 08:32:42 2021
Total number of signatures: 8595814

Platform information
--------------------
uname: Linux 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.7 (1.2.7), compile flags: a9

Build information
-----------------
GNU C: 4.8.5 20150623 (Red Hat 4.8.5-44) (4.8.5)
Engine flevel: 125, dconf: 125

# Freshclam errors on new instantiated instance:
WARNING: You are still on cool-down until after: 2021-12-02 07:45:48
Wed Dec  1 11:02:45 2021 -> --------------------------------------
Wed Dec  1 11:02:45 2021 -> Current working dir is /var/lib/clamav/
Wed Dec  1 11:02:45 2021 -> Can't open freshclam.dat in /var/lib/clamav
Wed Dec  1 11:02:45 2021 -> It probably doesn't exist yet. That's ok.
Wed Dec  1 11:02:45 2021 -> Failed to load freshclam.dat; will create a new freshclam.dat
Wed Dec  1 11:02:45 2021 -> Creating new freshclam.dat
Wed Dec  1 11:02:45 2021 -> Saved freshclam.dat
Wed Dec  1 11:02:45 2021 -> ClamAV update process started at Wed Dec  1 11:02:45 2021
Wed Dec  1 11:02:45 2021 -> Current working dir is /var/lib/clamav/
Wed Dec  1 11:02:45 2021 -> WARNING: DNS Update Info disabled. Falling back to HTTP mode.
Wed Dec  1 11:02:45 2021 -> Current working dir is /var/lib/clamav/
Wed Dec  1 11:02:45 2021 -> check_for_new_database_version: Local copy of daily found: daily.cvd.
Wed Dec  1 11:02:45 2021 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/daily.cld
Wed Dec  1 11:02:45 2021 -> Saved freshclam.dat
Wed Dec  1 11:02:45 2021 -> ERROR: remote_cvdhead: Malformed CVD header (too short)
Wed Dec  1 11:02:45 2021 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/daily.cvd
Wed Dec  1 11:02:45 2021 -> OK
Wed Dec  1 11:02:45 2021 -> daily database version obtained using HTTP GET: 26369
Wed Dec  1 11:02:45 2021 -> daily.cvd database is up-to-date (version: 26369, sigs: 1948295, f-level: 90, builder: xxxxxxx)
Wed Dec  1 11:02:45 2021 -> fc_update_database: daily.cvd already up-to-date.
Wed Dec  1 11:02:45 2021 -> Current working dir is /var/lib/clamav/
Wed Dec  1 11:02:45 2021 -> check_for_new_database_version: Local copy of main found: main.cvd.
Wed Dec  1 11:02:45 2021 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/main.cld
Wed Dec  1 11:02:45 2021 -> Saved freshclam.dat
Wed Dec  1 11:02:45 2021 -> ERROR: remote_cvdhead: Malformed CVD header (too short)
Wed Dec  1 11:02:45 2021 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/main.cvd
Wed Dec  1 11:02:45 2021 -> OK
Wed Dec  1 11:02:45 2021 -> main database version obtained using HTTP GET: 62
Wed Dec  1 11:02:45 2021 -> main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: xxxxxxxx)
Wed Dec  1 11:02:45 2021 -> fc_update_database: main.cvd already up-to-date.
Wed Dec  1 11:03:05 2021 -> --------------------------------------
Wed Dec  1 11:03:05 2021 -> freshclam daemon 0.103.4 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Wed Dec  1 11:03:05 2021 -> ClamAV update process started at Wed Dec  1 11:03:05 2021
Wed Dec  1 11:03:05 2021 -> WARNING: DNS Update Info disabled. Falling back to HTTP mode.
Wed Dec  1 11:03:05 2021 -> WARNING: FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Wed Dec  1 11:03:05 2021 -> This means that you have been rate limited or blocked by the CDN.
Wed Dec  1 11:03:05 2021 ->  1. Verify that you're running a supported ClamAV version.
Wed Dec  1 11:03:05 2021 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Wed Dec  1 11:03:05 2021 ->  2. Run FreshClam no more than once an hour to check for updates.
Wed Dec  1 11:03:05 2021 ->     FreshClam should check DNS first to see if an update is needed.
Wed Dec  1 11:03:05 2021 ->  3. If you have more than 10 hosts on your network attempting to download,
Wed Dec  1 11:03:05 2021 ->     it is recommended that you set up a private mirror on your network using
Wed Dec  1 11:03:05 2021 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Wed Dec  1 11:03:05 2021 ->     CDN and your own network.
Wed Dec  1 11:03:05 2021 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Wed Dec  1 11:03:05 2021 ->     it will not be granted.
Wed Dec  1 11:03:05 2021 -> WARNING: You are still on cool-down until after: 2021-12-02 11:02:45
Wed Dec  1 11:03:05 2021 -> --------------------------------------

**Comment by finchy** [comment]
Freshclam will update successfully after the cooldown.  You are rate limited by host, not by IP

**Comment by benthorner** [comment]
Hey there, we're experiencing this as well using `freshclam`: dedicated AWS external IPs, only a couple of requests per day, yet we get 429s. Sounds like this might be because are external IPs are part of a more general AWS block.

@finchy is that what you mean by "host" i.e. AWS, Google, etc?

It's a problem for us as we're running `freshclam` as part of a Docker image build, so if it silently fails with a 429 we end up with an image that has an empty signature DB 😬. Is there a way to get `freshclam` to return a non-zero exit status in this scenario? It's quite hard to track down the problem when it silently continues.

**Comment by finchy** [comment]
If you are using 0.103.4, it has nothing to do with the IP

**Comment by trunkshow** [comment]
Thanks for replying.

Just to understand, what are our instances being rate limited by when you say "rate limited by host"? Can you please explain?  We run a lot of instances, I admit.

The 0.103.4 update is rate limiting our instances to 1x per day, which logging confirms. 

I pasted the freshclam.conf settings that show "Checks 12" and confirm that logging shows instances are only checking for updates every 2 hours.  

To clarify, these are Private AWS cloud instances that, with the 0.103.4 update, log being rate limiting even though configuration has a Private Mirror setting for an internal VPC S3 bucket, where our organization drops updated daily and main files.  Which is what confuses me.  Is it the dns query checking for the latest versions that is being denied?  Can I disable that?

I'm just trying to understand.  We install the clamav on an image and then instantiate multiple instances from it, all having our base, environmental configurations.  Is it the machine_id setting on our hosts, or a freshclam key on our image that makes all our instances look like the same host and we should reset it?  Should we not install clamav on our images?  Are you free to say?

**Comment by finchy** [comment]
Did you copy your config from box to box?  Or did you independently set up ClamAV on each ec2 instance?

—

**Comment by trunkshow** [comment]
Since ClamAV is installed only once on an instance, from which an Image is then built, and all of our instances are then created from that one image already having ClamAV installed, I'd say my answer is like your first option, except for the copy part.  There isn't a need to copy a config from box to box, as every instance has the exact same configuration as the initial instance.  We didn't know there was a unique key on install, if that's where this is going.

**Comment by finchy** [comment]
Correct

—

**Comment by micahsnyder** [comment]
Hi @trunkshow. Apologies for the slow reply here. We're still on holiday break for a few more days.  But I saw your message and thought I spotted a new bug in the `freshclam` log.  I don't believe you're getting rate limited at all, but that some issue with error handling in `freshclam` when using the `PrivateMirror` option instead of the more common `DatabaseMirror` option is falsely reporting a failure.

For context, here's the difference between `DatabaseMirror` and `PrivateMirror`...
`DatabaseMirror`:
- Checks for updates using a DNS query.  If that fails, it will fallback to HTTP mode where it attempts to download the first 512 bytes of the database `.cvd` file so it can peek at the file header to see the version before choosing to download the whole file.
- If there is an update available, it will attempt to download one or more `.cdiff` database patch files.  If that fails, it will attempt to download the whole database `.cvd` file.

`PrivateMirror`:
- Only checks for updates using the 512-byte header check, described above.
- First checks for a copy of the database `.cld` file.  If that fails, it will try for the `.cvd` file.  It checks the `.cld` version first, because if you're using `freshclam` to maintain the databases hosted by your private mirror, your `freshclam` client will replace the compressed `.cvd` file with a decompressed `.cld` file after the first update, so the `.cld` file is more likely to exist.

What I'm seeing in your log:
```log
Wed Dec 1 11:02:45 2021 -> check_for_new_database_version: Local copy of main found: main.cvd.
Wed Dec 1 11:02:45 2021 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/main.cld
Wed Dec 1 11:02:45 2021 -> Saved freshclam.dat
Wed Dec 1 11:02:45 2021 -> ERROR: remote_cvdhead: Malformed CVD header (too short)
Wed Dec 1 11:02:45 2021 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/main.cvd
Wed Dec 1 11:02:45 2021 -> OK
```

^Here you can see that it attempts to download the `.cld` file for `main` first.  That fails in a weird way, claiming the CVD header is "malformed", "too short". It then goes on to try the `.cvd` file which succeeds. 

I think what's happening is that Amazon S3 isn't reporting a 404 for the `main.cld` or `daily.cld` files. Where `freshclam` should be reporting a "file not found" for `main.cld`, [here](https://github.com/Cisco-Talos/clamav/blob/main/libfreshclam/libfreshclam_internal.c#L1047), it instead goes on successfully thinking it downloaded the CVD header for `main.cld` and then fails [here](https://github.com/Cisco-Talos/clamav/blob/main/libfreshclam/libfreshclam_internal.c#L1074) with "Malformed CVD header (too short)". 

I suspect that either you have a small or malformed "main.cld" and "daily.cld" file in your S3 bucket, or that S3 simply fails to return a 404 when the file doesn't exist. 

If you indeed do not have `*.cld` versions of daily or main databases yet, the log should look like this:
```log

~/clams/0.103.4 took 14s
❯ ./bin/freshclam
ClamAV update process started at Mon Jan  3 11:30:36 2022
Pruning unwanted or deprecated database file bytecode.cvd.
WARNING: DNS Update Info disabled. Falling back to HTTP mode.
Trying to retrieve CVD header from http://localhost:8000/daily.cld
Time:    0.0s, ETA:    0.0s [========================>]       452B/452B
WARNING: remote_cvdhead: file not found: http://localhost:8000/daily.cld
Trying to retrieve CVD header from http://localhost:8000/daily.cvd
Time:    0.0s, ETA:    0.0s [========================>]       512B/512B
OK
daily database available for update (local version: 26348, remote version: 26411)
Time:    0.2s, ETA:    0.0s [========================>]   54.73MiB/54.73MiB
Testing database: '/home/micasnyd/clams/0.103.4/share/clamav/tmp.282944af61/clamav-4d59c3d45caddf71972746ad90b1f9c6.tmp-daily.cvd' ...
Database test passed.
daily.cvd updated (version: 26411, sigs: 1968299, f-level: 90, builder: raynman)
Trying to retrieve CVD header from http://localhost:8000/main.cld
Time:    0.0s, ETA:    0.0s [========================>]       452B/452B
WARNING: remote_cvdhead: file not found: http://localhost:8000/main.cld
Trying to retrieve CVD header from http://localhost:8000/main.cvd
Time:    0.0s, ETA:    0.0s [========================>]       512B/512B
OK
main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
```

Or if you do have **valid** `.cld` database files for daily and main hosted by your private mirror, the logs should look something like this example:
```log
~/clams/0.103.4 took 6s
❯ ./bin/freshclam
ClamAV update process started at Mon Jan  3 11:37:20 2022
Pruning unwanted or deprecated database file bytecode.cvd.
WARNING: DNS Update Info disabled. Falling back to HTTP mode.
Trying to retrieve CVD header from http://localhost:8000/daily.cld
Time:    0.0s, ETA:    0.0s [========================>]       512B/512B
OK
daily database available for update (local version: 26348, remote version: 26411)
Time:    0.7s, ETA:    0.0s [========================>]  172.03MiB/172.03MiB
Testing database: '/home/micasnyd/clams/0.103.4/share/clamav/tmp.29e4f7e7f9/clamav-5277510b29e1684c49aafaa1b442d28c.tmp-daily.cld' ...
Database test passed.
daily.cld updated (version: 26411, sigs: 1968299, f-level: 90, builder: raynman)
Trying to retrieve CVD header from http://localhost:8000/main.cld
Time:    0.0s, ETA:    0.0s [========================>]       512B/512B
OK
main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
```

Next steps:
1. Please check if you are in fact serving `daily.cld` and `main.cld` from your S3 bucket. If you aren't, then I suspect S3 is failing to send a 404 when a file doesn't exist. If you are, make sure they're not corrupted somehow or empty or something.  And double-check that you're correctly updating your database set for your private mirror: https://docs.clamav.net/appendix/CvdPrivateMirror.html#use-freshclam-to-serve-only-whole-database-files-from-a-private-mirror

2. Consider using `cvdupdate` to maintain your private mirror instead, and switch your `freshclam` clients to use `DatabaseMirror` instead of `PrivateMirror`.  You may wish to also set `DNSDatabaseInfo no` in your `freshclam.conf` so that `freshclam` will fail the DNS update and fallback to the HTTP 512-byte CVD header-check of your mirror's hosted files instead.  For more information on using `cvdupdate`, see https://docs.clamav.net/appendix/CvdPrivateMirror.html#use-cvdupdate-to-serve-whole-databases-and-database-patch-files-from-a-private-mirror

**Comment by trunkshow** [comment]
Hi @micahsnyder - you're right, I've never seen .cld files in our S3 bucket, just the main.cvd and daily.cvd.  Although I infrequently check freshclam since it's something that gets configured and then always works, I don't believe I've ever seen a WARNING for "file not found" when freshclam checks for the .cld files.  Our logs show that freshclam verifies a header from the .cvd and either logs "OK" or performs an update, so I assumed the log entry for the malformed header on the .cld file, although odd, was normal.  Thanks for the info on properly updating the mirror and the settings I can try.  I'll look into why we don't have .cld files - maybe it's just a script I can update.  I'll also try the settings you provided to see if it makes a difference.

**Comment by trunkshow** [comment]
@micahsnyder - I tried curling both files and can successfully get the daily.cvd from an instance with the rate limiting error.  When I curl the .cld file I did receive an "AccessDenied", but not a "403"  While my 2 vms have different O/Ss, they are both configured the same, except for the AL2 vm being the previous clamav version.  I haven't dug into the process that provides the updates to the bucket yet.  

# 403 response with v0.102.4 "not rate limited" Amazon Linux (AL2) vm
Tue Jan  4 22:24:10 2022 -> Received signal: wake up
Tue Jan  4 22:24:10 2022 -> ClamAV update process started at Tue Jan  4 22:24:10 2022
Tue Jan  4 22:24:10 2022 -> WARNING: DNS Update Info disabled. Falling back to HTTP mode.
Tue Jan  4 22:24:10 2022 -> Reading CVD header (daily.cld): Tue Jan  4 22:24:10 2022 -> ERROR: remote_cvdhead: Unexpected response (403) from https://redacted.private.s3.bucket.url.amazonaws.com/daily.cld
Tue Jan  4 22:24:10 2022 -> Reading CVD header (daily.cvd): Tue Jan  4 22:24:10 2022 -> OK

# no 403 response with v0.103.4 "rate limited" Centos 7 vm
Tue Jan  4 17:18:26 2022 -> WARNING: Cool-down expired, ok to try again.
Tue Jan  4 17:18:26 2022 -> Trying to retrieve CVD header from https://redacted.private.s3.bucket.url.amazonaws.com/daily.cld
Tue Jan  4 17:18:26 2022 -> ERROR: remote_cvdhead: Malformed CVD header (too short)

# curl error on .cld from "rate limited instance"
curl -s -k1 https://redacted.private.s3.bucket.url.amazonaws.com/daily.cld
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>redacted</RequestId><HostId>redacted=</HostId></Error>

**Comment by micahsnyder** [comment]
403 access denied responses from AWS S3 could mean that the file exists but ACL for the file isn't set to public or something?  I'm not all that familiar with AWS configurations so I'll be of limited help, here.   

For you in the short term the key will be for S3 to return a 404 if the file isn't there and to actually host the CLD file if you can.  Or alternatively you can switch to use `cvdupdate` as suggested with the `freshclam` clients configured to use `DatabaseMirror` instead of `PrivateMirror` so that they don't try to download the CLD files. 

You have shown that freshclam in 0.102 tolerated the 403 response and treated it roughly the same as 404, but freshclam in 0.103 persists the failure even though the fallback to use the CVD file worked.  So we definitely have a bug to fix here as well.  I'll rename the ticket to reflect the freshclam issuee and we'll try to fix it as time permits.

**Comment by trunkshow** [comment]
@micahsnyder - I tested the DatabaseMirror option and it works.  Thank you for the assistance -
