### ISSUE TITLE
Lift blacklist on 54.175.142.145 please?

### ISSUE THREAD

**Issue by dp65** [Cisco-Talos/clamav#403]
Hi,
  Could you check if 54.175.142.145 is still blacklisted and if so, could you lift it? 
  Last week we addressed out issues which were causing us to be blacklisted (https://bugzilla.clamav.net/show_bug.cgi?id=12608).  We created a local private mirror of the definitions and pushed that out to all of our environments, so I think we should be hitting the ClamAV servers MUCH less often.  It should be about 1x/hour. Please let me know if it's more than that, so that I can find and stop any that I missed..
  -- Donivan

**Comment by micahsnyder** [comment]
Hi @dp65,
I've reached out to the CDN admin.  It's past close of business there, but they'll try and unblock the IP tomorrow.
-- Micah

**Comment by micahsnyder** [comment]
@dp65 it looks like you're down to about 80-100 requests per hour for `daily.cvd` / `daily-26378.cdiff` (1920-2500 requests per day). The previous bugzilla ticket claimed it was at around 25,000 per day so that does seem like an improvement.  The number you're at should drop even more once those clients actually get updates and no longer try to download every time they check if an update is available. 

Our CDN is configured to rate limit users at no more than 10/requests per hour for a given file.  We can't differentiate between user agents for ClamAV versions < 0.103.2 so those clients get rate limited by IP.  Freshclam clients on 0.103.2 and newer should be rate limited per client.  So using the newer ClamAV version should also reduce the chance of being rate-limited.

To try to get you over that hump where your clients are generally up-to-date and don't try to download every time they check for an update, we've manually unblocked your IP.  We'll check again tomorrow to see if your request rate dropped as I expect it will. 

**As a heads up**: ClamAV 0.102 and older are almost at EOL and will be actively blocked in early January.  If you have older ClamAV versions running, please upgrade soon or those will soon be blocked for exceeding EOL. Ref: https://blog.clamav.net/2021/12/reminder-clamav-0102-0101-end-of-life.html

**Comment by dp65** [comment]
@micahsnyder , Thank you for all that very useful information! I'll work on getting our ClamAV clients upgraded, but that effort won't be started until after the New Year's holidays.

**Comment by micahsnyder** [comment]
@dp65 I hope you had a good break. We're back from the holiday break over here. 

We went ahead and checked again and it looks like the download rate from your IP is good again.  We've removed you from the allow list so your IP will be treated like everyone else again.  

Re: EOL for 0.102 - we're past the official date for EOL but we haven't enforced the block yet for this version. We'll be blocking it sometime after next week's patch release.
