### ISSUE TITLE
Logs starting with ~ are very confusing if log message is a path

### ISSUE THREAD

**Issue by dracan** [Cisco-Talos/clamav#436]
Sending a `SCAN` command to scan a specific file, and getting the following error message...

```
Mon Jan 24 08:49:25 2022 -> ~/files/b337f8a2-e03e-43f8-9774-2f0cca652d37.dat: Can't open file or directory ERROR
```

The error was just because my host's virus checking software was blocking it. However, before I realised what it was - I wasted a lot of time trying to work out why the path in the error message was wrong - ie. relative to my home (~) directory.

Digging further into the ClamD code to work out what was going on - I worked out that the codebase has a pattern of prefixing some logs with "~". This is super-confusing if the log message starts with a path.

**Comment by micahsnyder** [comment]
Hi @dracan this is longstanding bug in our `logg` logging mechanism when `LogTime` is enabled.  We have a ticket somewhere for it, though I was having trouble finding it. 

The log message previous is to indicate the log-level, and is supposed to be reformatted with:
- `!` --> `ERROR: `
- `^` --> `WARNING: `
- and no prefix for the ones for Info, Verbose, or Debug levels. 

My current idea for how to fix this is to change our `logg()` function from:
```c
int logg(const char *str, ...)
```
to
```c
int logg(loglevel_t, const char *str, ...)
```
where `loglevel_t` would be a new enum containing DEBUG, VERBOSE, INFO, WARN, and ERROR.  And then replace use of the prefixes like `~` with use of these enums. 

Someone (maybe me) just needs to find time to work on it. 

See: https://github.com/Cisco-Talos/clamav/blob/main/common/output.c#L312-L317
And: https://github.com/Cisco-Talos/clamav/blob/main/common/output.c#L411-L423

**Comment by dracan** [comment]
Hi @micahsnyder. Thanks for the quick and detailed reply 🙂 I guess a quicker option if removing the ~ is a lot of work, is perhaps if there aren't too many places where a file path starts at the beginning of a log entry - maybe wrap the path in those particular logs in quotes? Your suggestion is obviously a much better longer-term one - but this might be a quick fix to avoid paths that look they they originate from the user's home directory.

**Comment by micahsnyder** [comment]
That's a good point @dracan , we could at least put a space or something.

**Comment by mko-x** [comment]
Hi @micahsnyder & @dracan 

I would like to contribute to clamav and this issue is marked as good-first-bug. 

I was digging into the code and I was thinking about a possible quick solution.

At first I was thinking about the quickest solution like replacing all occurrences of '_logg("~_' in the src with '_logg("~ _'. But as I checked the logic, it seems like any loglevel information is removed within the `logg()`method for file logging. The buffer is always shifted in the area you highlighted here -> https://github.com/Cisco-Talos/clamav/blob/main/common/output.c#L411-L423 which means to me, the loglevel is not visible.

Only for logging in foreground loglevels might be written like seen by @dracan at https://github.com/Cisco-Talos/clamav/blob/main/common/output.c#L437

I provided a PR #444 - which cleans the output here.

In general I would prefer the solution with
```c
int logg(loglevel_t, const char *str, ...)
```
what needs a little more refactoring then for all the calls. So there will be a lot of files affected. Maybe there will be a new public method with the signature like given above first and then the calls could be changed in parts/chunks to not touch all the files at once? 

Maybe you have some idea? :D

**Comment by micahsnyder** [comment]
Hi @mko-x thanks for volunteering to help fix this issue @dracan identified with the absolute-relative path confusion and also for your interest in working on fixing the bug in `logg()`.  I or one of my teammates will review your PR soon.

I agree, changing all of the calls to use the new interface will touch so many files.  I think it's the right thing to do.  If `logg()` were in a public API that downstream products use, we'd need to maintain backwards compatibility and turn `logg()` into a shim that calls the new logging function with the level, but since this code is all internal to clamav's for use only by our command-line programs, I have no qualms about changing it all at once.

With a tool like vscode's global search & replace, it shouldn't be hard to do something like this for each logg special character...
> search: `logg("~`
> replace `logg(INFO, "`

...and knock them out in one pass. 

After you've handled all the ones with a special character, you'll probably also have to do one pass with:
> search: `logg("`
> replace `logg(INFO, "`

To get any that don't use a special character.

The more difficult part of the task will be rewriting `logg()` to use that parameter instead of parsing the message for the special character. I think it won't be so bad though.

Thanks again for volunteering!

**Comment by mko-x** [comment]
Thank you for the reply @micahsnyder 

So for the desired new logg method, we may discuss the available log variants first. Besides the ones found in the `legend`area

```c
/*
 * legend:
 *  ! - ERROR:
 *  ^ - WARNING:
 *  ~ - normal
 *  # - normal, not foreground (logfile and syslog only)
 *  * - verbose
 *  $ - debug
 *  none - normal
 *
 *	Default  Foreground LogVerbose Debug  Syslog
 *  !	  yes	   mprintf     yes      yes   LOG_ERR
 *  ^	  yes	   mprintf     yes	yes   LOG_WARNING
 *  ~	  yes	   mprintf     yes	yes   LOG_INFO
 *  #	  yes	     no	       yes	yes   LOG_INFO
 *  *	  no	   mprintf     yes	yes   LOG_DEBUG
 *  $	  no	   mprintf     no	yes   LOG_DEBUG
 *  none  yes	   mprintf     yes	yes   LOG_INFO
 */
```

I found another `@`prefix in `mprintf` for `error with logging` at 
https://github.com/Cisco-Talos/clamav/blob/main/common/output.c#L484
and 
https://github.com/Cisco-Talos/clamav/blob/main/common/output.c#L548

But there is no difference in handling `!`and `@` in `mprintf` so this might be ignored.

To keep existing functionality I would think of an enum like

```c
/*
 * legend:
 * NAME     OLD        EXPLAIN
 * INFO     none or ~   normal
 * INFO_NF  #           normal, no foreground
 * DEBUG    *           debug, verbose
 * DEBUG_NV $           debug, non-verbose
 * WARNING  ^           warning
 * ERROR    !           error
 */
enum loglevel_t{
    INFO, 
    INFO_NF, 
    DEBUG, 
    DEBUG_NV, 
    WARNING, 
    ERROR
};
```

**Comment by mko-x** [comment]
I created a new PR for this issue with the suggested changes by @micahsnyder at #445
