### ISSUE TITLE
WARNING: Your ClamAV installation is OUTDATED! WARNING: Local version: 0.103.2 Recommended version: 0.103.5 on Pfsense

### ISSUE THREAD

**Issue by gulfamaurangzeb** [Cisco-Talos/clamav#451]
WARNING: Your ClamAV installation is OUTDATED! WARNING: Local version: 0.103.2 Recommended version: 0.103.5 on Pfsense

**Comment by unicorn-lady** [comment]
Hello,

We are seeing the same issue since a few days. We are running ClamAV on AWS lambda. It looks like we cannot reach `http://database.clamav.net/main.cvd` to update our database. The error we are getting is:

```
Error: {\"stdout\":\"Current working dir is /tmp\\nClamAV update process started at Wed Feb  2 14:47:48 2022\\nUsing IPv6 aware code\\nMax retries == 3\\nQuerying current.cvd.clamav.net\\nTTL: 129\\nSoftware version from DNS: 0.103.5\\nDON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav\\nRetrieving http://database.clamav.net/main.cvd\\nIgnoring mirror 104.16.218.84 (due to previous errors)\\nTrying to download http://database.clamav.net/main.cvd (IP: 104.16.219.84)\\nQuerying main.0.105.0.0.6810DB54.ping.clamav.net\\nTrying again in 5 secs...\\nQuerying current.cvd.clamav.net\\nTTL: 1787\\nSoftware version from DNS: 0.103.5\\nDON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav\\nRetrieving http://database.clamav.net/main.cvd\\nIgnoring mirror 104.16.218.84 (due to previous errors)\\nTrying host database.clamav.net (104.16.219.84)...\\nTrying to download http://database.clamav.net/main.cvd (IP: 104.16.219.84)\\nQuerying main.0.105.0.0.6810DB54.ping.clamav.net\\nTrying again in 5 secs...\\nQuerying current.cvd.clamav.net\\nTTL: 1697\\nSoftware version from DNS: 0.103.5\\nDON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav\\nRetrieving http://database.clamav.net/main.cvd\\nIgnoring mirror 104.16.218.84 (due to previous errors)\\nTrying host database.clamav.net (104.16.219.84)...\\nTrying to download http://database.clamav.net/main.cvd (IP: 104.16.219.84)\\nQuerying main.0.105.0.0.6810DB54.ping.clamav.net\\nGiving up on database.clamav.net...\\nUpdate failed. Your network may be down or none of the mirrors listed in freshclam.conf is working. Check https://www.clamav.net/documents/official-mirror-faq for possible reasons.\\n\",\"stderr\":\"WARNING: Your ClamAV installation is OUTDATED!\\nWARNING: Local version: 0.101.4 Recommended version: 0.103.5\\nWARNING: getfile: Unknown response from database.clamav.net (IP: 104.16.219.84): HTTP/1.1 403 \\nWARNING: Can't download main.cvd from database.clamav.net\\nWARNING: Your ClamAV installation is OUTDATED!\\nWARNING: Local version: 0.101.4 Recommended version: 0.103.5\\nWARNING: getfile: Unknown response from database.clamav.net (IP: 104.16.219.84): HTTP/1.1 403 \\nWARNING: Can't download main.cvd from database.clamav.net\\nWARNING: Your ClamAV installation is OUTDATED!\\nWARNING: Local version: 0.101.4 Recommended version: 0.103.5\\nERROR: getfile: Unknown response from database.clamav.net (IP: 104.16.219.84): HTTP/1.1 403 \\nERROR: Can't download main.cvd from database.clamav.net\\n\",\"code\":58,\"error\":{\"killed\":false,\"code\":58,\"signal\":null,\"cmd\":\"freshclam -v --log=/tmp/freshclam.log --datadir=/tmp/ --config-file=freshclam.conf\"}}\n
```

When we try to get to this address by browser, we see a CloudFlare browser check, and the file downloads correctly. It gets blocked by 403 when using cli.

Please let us know if this problem will be resolved soon.

**Comment by micahsnyder** [comment]
@gulfamaurangzeb the warning you reported is non-fatal. It is advising you to upgrade because there are security fixes in the newer versions. But your 0.103.2 version should still work.  This is not a bug, so I'm closing this ticket.

@unicorn-lady if you're getting 403'd as of this week, it's because you're using 0.102 or older which have exceeded End of Life (EOL) and are now actively blocked from downloading updates. Chances are you've been receiving the warning message about upgrading for much longer and are only just now being blocked from downloading database updates. See our EOL policy, for details: https://docs.clamav.net/faq/faq-eol.html 

I'm aware that you technically can download the databases with a browser.  But *Please* do not use a browser to update your databases.  Updates through freshclam are much more efficient than a plain download.  Incremental updates through freshclam saves us a lot of cost on bandwidth, especially with features added in ClamAV 0.103.2 and newer.  Please upgrade your installation to a supported version,. ClamAV 0.103 LTS or 0.104, to regain access to the signature database feed.
