### ISSUE TITLE
ClamAV docker & GKE deployment error connection ECONNREFUSED when I run docker image

### ISSUE THREAD

**Issue by ahmedzak7** [Cisco-Talos/clamav#493]
Iam trying to build a ClamAV malware scanner docker image that runs on a squid proxy and I get

!NotifyClamd: Can't connect to clamd on 127.0.0.1:3310: Connection refused and error: connect ECONNREFUSED 127.0.0.1:3310 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1158:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 3310 }

Stopping ClamAV daemon: clamd. Clamav signatures not found in /var/lib/clamav ... failed! Please retrieve them using freshclam ... failed! Then run 'invoke-rc.d clamav-daemon start' ... failed!

This is my dockerfile :

```dockerfile
FROM node:17.6.0-bullseye-slim
# Set versions
ENV CLOUD_SDK_VERSION=372.0.0
# Install base packages 
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
RUN apt-get update && \
    apt-get install -y build-essential clamav-daemon clamav-freshclam curl python3 sudo && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /usr/local/gcloud && \
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    tar -C /usr/local/gcloud -xvf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    ln -s /lib /lib64 && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    mkdir -p /home/node/app && \
    chown -R node:node /home/node/app && \
    chmod 777 /var/log/clamav/freshclam.log && \
    chmod 777 /var/lib/clamav && \
    echo "TCPSocket 3310" >> /etc/clamav/clamd.conf && \
    echo "TCPAddr 127.0.0.1" >> /etc/clamav/clamd.conf && \
    echo "User node" >> /etc/clamav/clamd.conf && \
    echo "DatabaseOwner node" >> /etc/clamav/freshclam.conf && \
    echo "HTTPProxyServer squid-proxy.neds.local" >> /etc/clamav/freshclam.conf && \
    echo "HTTPProxyPort 3128"  >> /etc/clamav/freshclam.conf && \
    echo "node ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/node
# Bring in app code
WORKDIR /home/node/app
COPY --chown=node:node . .
# Set up app
RUN npm config set python $(which python3) && \
    npm install
# Run the rest as the node user
USER 1000
CMD ["/bin/bash", "bootstrap.sh"]
```
and this is bootstrap.sh :
```bash
#!/bin/bash
sudo service clamav-freshclam stop && \
sudo freshclam && \
sudo service clamav-freshclam start && \
sudo service clamav-daemon force-reload && \
npm start
```
It fails when I docker run it OR when i deploy it on a GKE cluster , all ips required are whitelisted on the squid

**Comment by micahsnyder** [comment]
I just cleaned up your issue report to make it readable.  In the future, you can use three back-ticks before and after your code for a multi-line code block. 
For example, this
````
```dockerfile
FROM node:17.6.0-bullseye-slim
# Set versions
...
```
````
will render like this:
```dockerfile
FROM node:17.6.0-bullseye-slim
# Set versions
...
```
The Preview tab can help you make sure it looks just how you like it before you save.

Your report here is more like a question about how to set up clamav than a bug report.  Questions should really go to the mailing list or maybe the Discord chat: https://docs.clamav.net/Introduction.html#mailing-lists-and-chat.

If `freshclam` is failing to download the databases, you should also check the freshclam.log file to find out what went wrong. 

You might also take a look at our Docker file: https://github.com/Cisco-Talos/clamav/blob/main/Dockerfile
and docker file scripts: https://github.com/Cisco-Talos/clamav/tree/main/dockerfiles
to compare notes.  You might find something there that will help.

I would also ask that when you run ClamAV docker containers, please mount the database directory with a volume so that new containers do not have to download the databases every time. The databases are a couple-hundred megabytes at this point, and downloading them each time you start a new container will waste a lot of bandwidth.  Some package distributions provide a base set of databases, but these can be out of date and may be too old to update using patches.  So I would not rely on the packages to start you off with recent databases.
We have some instructions that may help, here: https://docs.clamav.net/manual/Installing/Docker.html#persisting-the-virus-database-volume
