### ISSUE TITLE
ClamAV is not detecting eicar of ppt or pptx

### ISSUE THREAD

**Issue by manojgct84** [Cisco-Talos/clamav#516]
Describe the bug
----------------
When we pass an eicar ppt for pptx to clamav it gives a ok stream, But the expected is infected.

When the same file is passed to McAfee, it tells the file is infected.

How to reproduce the problem
----------------------------
1. Clamav Version :0.99
2. Download the ppt or pptx file from this github for testing: https://github.com/fire1ce/eicar-standard-antivirus-test-files
3. Pass the file to ClamAV to test the file.

The output from the ClamAV command:
   stream: OK

**Comment by MartinR-cF** [comment]
Hi ClamAV-Team, 
thanks for reporting the issue. Indeed we could reproduce the same.
Do you get feedback from other users or projects using ClamAV on this issue?
Would you have any plans to fix this in the code?
Is there anything we can support a fix?

with Best Regards
Martin

**Comment by MartinR-cF** [comment]
Hi ClamAV-Team,
for a fix of this issue we offer as a reward a bug bounty of €500,00.
Anyone interested in this? pls reply here to agree on details.

with Best Regards
Martin

**Comment by MartinR-cF** [comment]
Hi ClamTeam,
you can also reach out to me via email: 06_baud_fakultaet@icloud.com

thanks
Martin

**Comment by MartinR-cF** [comment]
@micahsnyder ,
at first thanks for your response and effort.
I'm supporting @bbasman with his response and proposal.

 thanks & with Best Regards

**Comment by micahsnyder** [comment]
@bbasman @MartinR-cF I'm sorry for the delay in responding to you.

Our threat research team added the signatures to detect the suspicious techniques used in those last few test files that we didn't detect before. 

They still don't detect the actual "eicar" content, so it doesn't mention "eicar". But they're not simple signatures that would only detect the test files.  The signatures should actually protect against other malware using the same technique. So that's actually the best possible news!

This is what testing on my laptop showed. 
```
/mnt/c/Users/micah/Downloads/eicar-standard-antivirus-test-files-master/eicar-excel-dde-cmd-powershell-echo.xls: Xls.Exploit.Agent-9987934-0 FOUND
/mnt/c/Users/micah/Downloads/eicar-standard-antivirus-test-files-master/eicar-excel-dde-cmd-powershell-echo.xlsx: Xml.Exploit.DDE_Abuse-9987933-0 FOUND
/mnt/c/Users/micah/Downloads/eicar-standard-antivirus-test-files-master/eicar-powerpoint-action-powershell-echo.ppt: Ppt.Exploit.Agent-9987931-1 FOUND
/mnt/c/Users/micah/Downloads/eicar-standard-antivirus-test-files-master/eicar-powerpoint-action-powershell-echo.pptx: Xml.Exploit.External_Relationship_Abuse-9987932-1 FOUND
```
