### ISSUE TITLE
Version 0.105 load yara regex failed

### ISSUE THREAD

**Issue by cobragege** [Cisco-Talos/clamav#594]
Describe the bug
----------------
version:0.105
yara:
```yara
rule y_test
{
	meta:
		description = "test for clamav"
		license = ""
		author = ""
		date = "2021/02/07"
		score = 50
        
	strings:
		$string1 = /\.ssh\/authorized_keys|Content-Transfer-Encoding: Binary/ ascii
	condition:
		$string1
}
```

When I use clamscan load one yara file like above mentioned, it report error log like this:
`
LibClamAV Error: PCRE subsig mismatched '/' delimiter
`
however all work well with 0.104.1 version.
Then I've track into the error point through lldb, the context tell me $string1 went into [pcre subsignatures ](https://docs.clamav.net/manual/Signatures/LogicalSignatures.html#pcre-subsignatures).
but I've read its parent section says:**ClamAV stores all body-based (content-based) signatures in a hexadecimal format, with exception to ClamAV's YARA rule support**

conclusion:
maybe $string1 contains escaped slash and colon, which cause it went into pcre subsignatures, and then the load action broke down. Please correct me if i misunderstood,or is there a correct way to fix,which i haven't found it yet ,thanks.

How to reproduce the problem
----------------------------
`
clamscan --scan-html=no  -d  path_to_test.yar  --dumpcerts --debug --verbose --max-filesize=2000M --max-scansize=2000M --max-files=2000000 --max-recursion=2000000 --max-embeddedpe=2000M --max-iconspe=2000000 path_to_sample
`

**Comment by ragusaa** [comment]
Thank you for the bug report.  We have a ticket planned for our next release to address other yara issues, I'll add this to it.

Thanks,
Andy

**Comment by micahsnyder** [comment]
@huzhanchi @ragusaa I was waiting for something and thought I'd take a quick look at this. I found that this issue isn't quite what it seems, and impacts both Yara rules and also LDB signatures containing a `/` before a `:` within the regex string. 

For LDB sigs, a simple signature like this would fail to load because of that `/` + `:` in the string:
```
CLAM-2001;Engine:81-255,Target:0;1;68656c6c6f20;0/hello blee/blah: bleh/
```

In previous versions this bug didn't impact Yara rules because the function we use to tokenize subsignatures for an offset value wasn't used with Yara regex strings.  After the rework to tidy up the database load code, it started to do that -- and that revealed the bug.

I just put in a fix that addresses the issue for both LDB and Yara rules, and has a test testing each.  We're too low on time for review and QA to get this into our upcoming patch version, but maybe the next patch version or at least the next feature release.
