### ISSUE TITLE
My freshclam is blocked to download Clamav signatures

### ISSUE THREAD

**Issue by gklipel** [Cisco-Talos/clamav#708]
Hi!
Our firewall is blocked to download Clamav official database, freshclam verbose log shows:
WARNING: Tue Sep 27 11:05:59 2022 -> fc_download_url_databases: fc_download_url_database failed: Forbidden; Blocked by CDN (17)
ERROR: Tue Sep 27 11:05:59 2022 -> Database update process failed: Forbidden; Blocked by CDN

Which data do I need to inform you to investigate the case?

**Comment by micahsnyder** [comment]
Hi @gklipel

We will need your public IP address in order to identify the cause of the block in our logs. 

If you could also provide the output from `clamconf -n` that may help.   Specifically I am intereste dto know which version of clamav you are using.  Some versions are blocked they are past end of life: https://docs.clamav.net/faq/faq-eol.html#version-support-matrix

Please also see https://docs.clamav.net/faq/faq-freshclam.html#http-error-codes

**Comment by gklipel** [comment]
Hi! Thanks.

Software settings
-----------------
Version: 0.105.1
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR

IP:
![Captura de tela 2022-09-28 153115](https://user-images.githubusercontent.com/5332759/192861127-b384fd40-7ff3-45d2-ab95-12b89222a8a8.png)

**Comment by micahsnyder** [comment]
@gklipel  are you still having issues?  I dropped the ball and failed to request the lookup as soon as you provided the public IP.  We looked today and found no events within the last 7 days.

**Comment by gklipel** [comment]
Hi! Not anymore, sorry, I usually don't look notifications!

Thanks and best regards!

**Comment by micahsnyder** [comment]
Okay, great!

Take care!
