### ISSUE TITLE
Off-line documentation | Non-existing resource in link's target

### ISSUE THREAD

**Issue by Ricky-Tigg** [Cisco-Talos/clamav#739]
Hello. [Here](https://github.com/Cisco-Talos/clamav), the [link](https://github.com/Cisco-Talos/clamav/blob/main/docs/html/UserManual.html) for _off-line_ leads to a page reporting _The 'Cisco-Talos/clamav' repository doesn't contain the 'docs/html/UserManual.html' path in 'main'._.

**Comment by micahsnyder** [comment]
Hi @Ricky-Tigg 

You're correct, `docs/html/UserManual.html` doesn't exist in git.  This is intentional. The documentation is only bundled with clamav when we build the release tarball. For example https://www.clamav.net/downloads/production/clamav-0.105.1.tar.gz or https://www.clamav.net/downloads/production/clamav-1.0.0-rc.tar.gz

That said, the link in https://github.com/Cisco-Talos/clamav/blob/main/README.md#documentation--faq for the main page of the offline documentation is incorrect.  It used to be `UserManual.html`, but it is now `index.html`.

I will submit a PR to fix it. 

Thanks for the report!
