### ISSUE TITLE
Signature was not loaded on clamav 0.103

### ISSUE THREAD

**Issue by SuganthDTR** [Cisco-Talos/clamav#848]
Hi team,

As part of the PROD VM OS patching on 25th Feb, clamd upgraded to clamav 0.103 version but Signature was not loaded. This impacted our live environment and the issue got resolved once we ran sudo freshclam. Since it is an clamav bug. This is to find the root cause and how we can avoid it on future.

current version :
clamd-0.103.8-1.el8.x86_64
clamav-filesystem-0.103.8-1.el8.noarch
clamav-0.103.8-1.el8.x86_64
clamav-update-0.103.8-1.el8.x86_64
clamav-data-0.103.8-1.el8.noarch
clamav-lib-0.103.8-1.el8.x86_64
clamav-devel-0.103.8-1.el8.x86_64

ERROR LOGS :
+++ Started at Mon Feb 27 08:30:49 2023
Received 0 file descriptor(s) from systemd.
clamd daemon 0.103.8 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Log file size limited to 1048576 bytes.
Reading databases from /var/lib/clamav
Not loading PUA signatures.
Bytecode: Security mode set to "TrustSigned".
ERROR: Can't verify database integrity

**Comment by micahsnyder** [comment]
> the issue got resolved once we ran sudo freshclam

How did you first install the signature databases before you ran sudo freshclam?

**Comment by SuganthDTR** [comment]
we have not manually installed any signature database. Everything was working fine when we were running with previous version of clam. During the PROD VM OS patching clamd upgraded to clamav 0.103.8.

we tried to start the clamd but the status is "failed" but it created clamd pid file. so we ran sudo freshclam as per the recommendation below since we were seeing issue on updating signature.

https://docs.clamav.net/faq/faq-troubleshoot.html

"After ClamAV is installed, then what? How do I update / refresh the virus database?
You will need to edit the freshclam.conf.example file located in /usr/local/etc. Once that is done, you will need to run a sudo freshclam to download the signatures. You will need to run the command to update signatures often so that ClamAV has the most up to date signatures."

systemctl start clamd@scan.service
Job for clamd@scan.service failed because the control process exited with error code.
See "systemctl status clamd@scan.service" and "journalctl -xe" for details.

**Comment by micahsnyder** [comment]
@SuganthDTR What I mean to ask is that if you installed clamav from ubuntu or debian or wherever and the signature databases were included as a part of their distribution package.   If so, then it sounds like an issue with that distribution's package, and not something we can fix here.

**Comment by SuganthDTR** [comment]
@micahsnyder I believe distribution package will get download from your server only. so who is the responsible for this. Could you please advise us 

How can we ensure that distribution's package were successfully downloaded ?

Was there any issues raised for this version by other BU's as we got impacted multiple prod servers with the same clamav version.

**Comment by micahsnyder** [comment]
@SuganthDTR sorry about the delay replying. 

The package `clamav-data-0.103.8-1.el8.noarch` you mention above is probably where the clamav databases came from before you ran `sudo freshclam`.   

Our team does not make this package or any of the other packages referenced above.   

The package names look like they come from EPEL.   My thought is that the `clamav-data-0.103.8-1.el8.noarch` package may have an issue.  You may wish to report this to the EPEL team that maintains those packages for RHEL/Fedora/Centos: 
- project page: https://src.fedoraproject.org/rpms/clamav
- issue tracker: https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&product=Fedora&product=Fedora%20EPEL&component=clamav
- clamav-0.103.8-3.el8 build information: https://koji.fedoraproject.org/koji/buildinfo?buildID=2156093

I am going to close this bug report because this issue isn't with packages provided by clamav or with the clamav source code.
